ServerName localhost

# Pass environment variables to CGI scripts.
# CGI スクリプトに環境変数を渡す。
PassEnv MURLOG_PROTOCOL

<Directory "/usr/local/apache2/htdocs">
    Options +ExecCGI
    AllowOverride All
    Require all granted
    AddHandler cgi-script .cgi
</Directory>
